### ISSUE TITLE
PDF generator font issues with some languages

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/conformance-questionnaire#34]
It looks like the font used to generate the PDF documents does not support Korean.

See: https://openchain-project.github.io/conformance-questionnaire/questionnaire-ko.pdf

The font files are locate here: https://github.com/OpenChain-Project/conformance-questionnaire/tree/master/scripts/fonts

and referenced here: https://github.com/OpenChain-Project/conformance-questionnaire/blob/6d013c39cd4f0613224c417342e67d8e2c8d2a6f/scripts/produce-pdf.js#L15

**Comment by shanecoughlan** [comment]
Yargh. However, I think it is OK to deploy the web app and to fix the PDF a little later. Usage is expected to be much lower.

**Comment by goneall** [comment]
After doing some research, the languages Japanese, Chinese and Korean require individual font files.  The script that produces the PDFs will need to be updated to choose different fonts based on the language.  

Most of the Korean fonts use OTF format.  Embedding OTF formats in the pdfs using PDFMake creates unusable PDF documents.  I'm not sure if this is an issue with PDF Make or with the PDF reader.

I am now looking for an acceptable open source ttf format Korean font.  Once I find one, I can update the script to resolve this issue.

**Comment by goneall** [comment]
Resolved with PR #36 

Not very happy with the look of the font, but it does render the PDF without error.

If anyone finds a better looking font, please open a PR or issue pointing to the font and I'll update the scripts.

Note that the font MUST be a ttf filetype and must have an acceptable license to be used within the scripts.
