### ISSUE TITLE
Conformance Questionnaire Showing Wrong Version (PDF)

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/conformance-questionnaire#41]
The PDF version of the conformance questionnaire as found on the certification web app incorrectly shows Version 1.2 when it instead maps to Version 2.0 of the spec.
https://openchain-project.github.io/conformance-questionnaire/questionnaire.pdf

**Comment by shanecoughlan** [comment]
Kate in CC for reference. 
Gary, can we run through this together?

**Comment by goneall** [comment]
It looks like we missed some of the "fine print" in the preamble text.

I created a PR #42 which corrects the issue.  The only change was changing the "1.2" to "2.0" in the preamble text.

Once it is merged, the problem will be fixed.

@shanecoughlan let me know if you'd like to go over any aspect of the fix.

**Comment by shanecoughlan** [comment]
That is so cool! Seems great to me. Sorry for the extra work.
