### ISSUE TITLE
language name translation for the remaining 6 languages

### ISSUE THREAD

**Issue by brandelune** [OpenChain-Project/conformance-questionnaire#63]
en,ja,fr,it,hi,es,he,ru
English,英語,Anglais,Inglese,अंग्रेज़ी,Inglés,אנגלית,Английский 
Simplified Chinese,簡体字,Chinois simplifié,Cinese semplificato,सरलीकृत चीनी,Chino simplificado,סינית פשוטה,Упрощенный китайский 
Traditional Chinese,繁体字,Chinois traditionnel,Cinese tradizionale,पारंपरिक चीनी,Chino tradicional,סינית מסורתית,Традиционный китайский
Korean,韓国語,Coréen,Coreano,कोरिअन,Coreano,קוריאנית,Корейский 
Japanese,日本語,Japonais,Giapponese,जापानी,Japonés,יפנית,Японский 
German,ドイツ語,Allemand,Tedesco,जर्मन,Alemán,גרמנית,Немецкий 
French,フランス語,Français,Francese,फ्रांसीसी,Francés,צרפתית,Французский 
Italian,イタリア語,Italien,Italiano,इतालवी,Italiano,איטלקית,Итальянский
Spanish,スペイン語,Espagnol,Spagnolo,स्पेनिश,Español,ספרדית,Испанский
Hindi,ヒンジ語,Hindi,Hindi,हिंदी,Hindi,הינדי,Хинди
Russian,ロシア語,Russe,Russo,रूसी,Ruso,רוסית,Русский 
Hebrew,ヘブライ語,Hébreu,Ebraico,हिब्रू,Hebreo,עברית,Иврит

**Comment by goneall** [comment]
I checked and the languages are already up to date.

Note that we only have WebApp translations for en, ja, and ko currently.
