### ISSUE TITLE
Current questionnaire does only allows conformance for organizations allowing contributions to FOSS projects.

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/conformance-questionnaire#7]
"Do you allow contributions of your employees to FOSS projects on behalf of the organization?”

This is a yes/no question. We expect all “yes” to conform. However, *not* allowing contributions on behalf of an organization is as valid as allowing contributions as a business decision. 

Suggested fix:
"Do you have a policy to explicitly permit or forbid contributions of your employees to FOSS projects on behalf of the organization?”

**Comment by goneall** [comment]
Originally raised by Shane on the conformance email distribution list.

**Comment by zvr** [comment]
I agree with the issue and the proposed fix.

**Comment by goneall** [comment]
The questionnaire has been updated with PR #8.  The updated question has also been uploaded to version 1.2 of the questionnaire in the certification application.
